/* EVZO — SEO pass
 * ===========================================================================
 *   node tools/seo.mjs
 *
 * Injects the machine-readable half of every page — canonical URL, Open Graph
 * URL, hreflang, and JSON-LD structured data — then writes sitemap.xml and
 * robots.txt.
 *
 * It is IDEMPOTENT. Everything it writes sits between marker comments and is
 * replaced wholesale on the next run, so running it twice does not duplicate a
 * single tag. Run it after editing any page's copy.
 *
 * THE RULE: with no config.site.baseUrl set, this emits no canonical, no
 * og:url, no sitemap and no absolute URL anywhere. A canonical pointing at a
 * domain that is not yours is worse than no canonical at all, and a sitemap
 * full of guessed URLs is worse than no sitemap. The structured data that does
 * not need a URL is still written, because it is useful on day one.
 *
 * Structured data written:
 *   index.html  Organization, WebSite, FAQPage  (the FAQ is really on the page)
 *   shop.html    ItemList of Products with real offers from the catalogue
 *   blog posts   handled by tools/blog.mjs, which owns their markup
 * ======================================================================== */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const CONFIG = createRequire(import.meta.url)(join(ROOT, "site", "config.js"));
const POSTS = JSON.parse(readFileSync(join(ROOT, "content", "blog.json"), "utf8")).posts;

const BASE = CONFIG.isSet(CONFIG.site.baseUrl)
  ? String(CONFIG.site.baseUrl).replace(/\/+$/, "")
  : null;

const abs = path => (BASE ? (path ? BASE + "/" + path.replace(/^\/+/, "") : BASE + "/") : null);

const BEGIN = "<!-- EVZO-SEO:BEGIN — generated by tools/seo.mjs, do not edit by hand -->";
const END = "<!-- EVZO-SEO:END -->";

/** Replace the generated block, or insert one just before </head>'s content. */
function inject(file, inner) {
  const path = join(ROOT, file);
  if (!existsSync(path)) { console.log("skipped (missing): " + file); return; }
  let html = readFileSync(path, "utf8");
  const block = BEGIN + "\n" + inner.trim() + "\n" + END;

  const b = html.indexOf(BEGIN);
  if (b !== -1) {
    const e = html.indexOf(END, b);
    html = html.slice(0, b) + block + html.slice(e + END.length);
  } else {
    /* These pages have no <head> element — they rely on the parser building
       one, which is valid HTML. So the block goes after the last <link> in the
       implicit head instead. */
    const anchor = html.lastIndexOf("<link ");
    const lineEnd = html.indexOf("\n", anchor);
    html = html.slice(0, lineEnd + 1) + block + "\n" + html.slice(lineEnd + 1);
  }
  writeFileSync(path, html);
  console.log("seo: " + file);
}

/** The head tags every page wants, given its path. */
function head(path, { noindex = false, image = "brand/og-home.png" } = {}) {
  const url = abs(path);
  const out = [];

  /* The share card. Absolute URLs only — WhatsApp, Facebook and Twitter all
     refuse a relative one, and a missing image is why a link preview falls
     back to a zoomed-in favicon. */
  const img = abs(image);
  if (img) {
    out.push(`<meta property="og:image" content="${img}">`);
    out.push(`<meta property="og:image:width" content="1200">`);
    out.push(`<meta property="og:image:height" content="630">`);
    out.push(`<meta property="og:image:alt" content="EVZO — personalised meal guides and recipe books">`);
    out.push(`<meta name="twitter:image" content="${img}">`);
  }
  if (url) {
    out.push(`<link rel="canonical" href="${url}">`);
    out.push(`<meta property="og:url" content="${url}">`);
    // One page serves both languages through the toggle, so both hreflangs
    // point at the same URL. That is correct for a client-side switch — it is
    // not two documents.
    out.push(`<link rel="alternate" hreflang="${CONFIG.site.locale}" href="${url}">`);
    out.push(`<link rel="alternate" hreflang="${CONFIG.site.altLocale}" href="${url}">`);
    out.push(`<link rel="alternate" hreflang="x-default" href="${url}">`);
  }
  out.push(`<meta name="robots" content="${noindex ? "noindex, nofollow" : "index, follow, max-image-preview:large, max-snippet:-1"}">`);
  return out;
}

const ld = obj => `<script type="application/ld+json">${JSON.stringify(obj)}</script>`;

/* ---- the organisation, referenced by everything else -------------------- */
const org = {
  "@type": "Organization",
  "@id": BASE ? BASE + "/#org" : undefined,
  name: CONFIG.site.legalName,
  alternateName: CONFIG.site.name,
  url: BASE || undefined,
  email: CONFIG.business?.supportEmail || undefined,
  sameAs: [CONFIG.links?.instagram].filter(Boolean),
  // Stated rather than implied: this brand is not a medical provider, and the
  // structured data should not let anyone infer otherwise.
  description: "Personalised meal-planning guides and recipe books for Greek and Cypriot kitchens. General wellness information, not medical or dietetic advice."
};

/* ---- index.html: the sales page ---------------------------------------- */
{
  const faq = [];
  const html = readFileSync(join(ROOT, "index.html"), "utf8");
  /* Pulled out of the page's own markup rather than retyped, so the rich
     result and the page can never say different things. Google treats a
     mismatch as a manual-action risk, and rightly. */
  const re = /<summary[^>]*>([\s\S]*?)<\/summary>\s*<p[^>]*>([\s\S]*?)<\/p>/g;
  let m;
  while ((m = re.exec(html))) {
    const q = m[1].replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();
    const a = m[2].replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();
    /* Answers rendered at runtime from config.js are a placeholder in the
       static markup. An FAQ rich result with an empty answer is worse than no
       rich result, so those questions are skipped rather than shipped blank. */
    const placeholder = !a || a.length < 12 || /^[—–-]+$/.test(a) || /NOT SET/i.test(a);
    if (q && !placeholder) faq.push({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } });
  }

  const graph = [org, {
    "@type": "WebSite",
    "@id": BASE ? BASE + "/#site" : undefined,
    name: CONFIG.site.name,
    url: BASE || undefined,
    publisher: BASE ? { "@id": BASE + "/#org" } : undefined,
    inLanguage: [CONFIG.site.locale, CONFIG.site.altLocale]
  }];
  if (faq.length) graph.push({ "@type": "FAQPage", mainEntity: faq });

  inject("index.html", [
    ...head("", { image: "brand/og-home.png" }),
    ld({ "@context": "https://schema.org", "@graph": graph })
  ].join("\n"));
  console.log("  FAQ entries found in the page: " + faq.length);
}

/* ---- shop.html: the catalogue ------------------------------------------- */
{
  const books = CONFIG.ebooks.books;
  const price = CONFIG.ebooks.singlePriceAmount;
  const cur = CONFIG.ebooks.currency;

  const items = books.map((b, i) => ({
    "@type": "ListItem",
    position: i + 1,
    item: {
      "@type": "Product",
      name: CONFIG.site.name + " " + b.name,
      description: b.blurb,
      brand: { "@type": "Brand", name: CONFIG.site.name },
      category: "Ebook",
      offers: {
        "@type": "Offer",
        price: price.toFixed(2),
        priceCurrency: cur,
        // Digital download, delivered by the owner. Availability is honest:
        // it is on sale, and nothing here claims a review or a rating,
        // because there are none.
        availability: "https://schema.org/InStock",
        url: abs("shop/") || undefined
      }
    }
  }));

  inject("shop/index.html", [
    ...head("shop/", { image: "brand/og-shop.png" }),
    ld({
      "@context": "https://schema.org",
      "@graph": [
        org,
        { "@type": "CollectionPage", name: "EVZO Shop", url: abs("shop.html") || undefined,
          about: "Recipe and training ebooks for Greek and Cypriot kitchens" },
        { "@type": "ItemList", name: "EVZO ebooks", numberOfItems: books.length, itemListElement: items }
      ]
    })
  ].join("\n"));
}

/* ---- blog.html: the index ------------------------------------------------ */
{
  const sorted = [...POSTS].sort((a, b) => b.date.localeCompare(a.date));
  inject("blog/index.html", [
    ...head("blog/", { image: "brand/og-blog.png" }),
    ld({
      "@context": "https://schema.org",
      "@graph": [
        org,
        {
          "@type": "Blog",
          name: "EVZO Blog",
          url: abs("blog/") || undefined,
          inLanguage: CONFIG.site.locale,
          blogPost: sorted.map(p => ({
            "@type": "BlogPosting",
            headline: p.title,
            datePublished: p.date,
            description: p.excerpt,
            url: abs("blog/" + p.slug + "/") || undefined
          }))
        }
      ]
    })
  ].join("\n"));
}

/* ---- the preview page must never be indexed ----------------------------- */
inject("_preview-reviews.html", head("_preview-reviews.html", { noindex: true }).join("\n"));

/* ---- sitemap and robots -------------------------------------------------- */
const pages = [
  { loc: "", priority: "1.0", freq: "weekly" },
  { loc: "shop/", priority: "0.9", freq: "weekly" },
  { loc: "blog/", priority: "0.8", freq: "weekly" },
  { loc: "legal/", priority: "0.3", freq: "yearly" },
  ...POSTS.map(p => ({ loc: "blog/" + p.slug + "/", priority: "0.7", freq: "monthly", lastmod: p.date }))
];

if (BASE) {
  writeFileSync(join(ROOT, "sitemap.xml"),
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    pages.map(p =>
      "  <url>\n" +
      `    <loc>${abs(p.loc)}</loc>\n` +
      (p.lastmod ? `    <lastmod>${p.lastmod}</lastmod>\n` : "") +
      `    <changefreq>${p.freq}</changefreq>\n` +
      `    <priority>${p.priority}</priority>\n` +
      "  </url>"
    ).join("\n") +
    "\n</urlset>\n");
  console.log("wrote sitemap.xml (" + pages.length + " urls)");

  writeFileSync(join(ROOT, "robots.txt"),
    "User-agent: *\n" +
    "Allow: /\n" +
    "Disallow: /_preview-reviews.html\n" +
    "Disallow: /ebooks/\n" +
    "Disallow: /content/\n\n" +
    "Sitemap: " + abs("sitemap.xml") + "\n");
  console.log("wrote robots.txt");
} else {
  /* robots.txt does not need the domain, so it is written either way — the
     preview page and the source folders should never be crawled. */
  writeFileSync(join(ROOT, "robots.txt"),
    "User-agent: *\n" +
    "Allow: /\n" +
    "Disallow: /_preview-reviews.html\n" +
    "Disallow: /ebooks/\n" +
    "Disallow: /content/\n\n" +
    "# Sitemap line is added by tools/seo.mjs once config.site.baseUrl is set.\n");
  console.log("wrote robots.txt (no sitemap line — config.site.baseUrl is not set)");
  console.log("\nSet config.site.baseUrl to your domain and run this again to get");
  console.log("canonical tags, hreflang, absolute og:url and sitemap.xml.");
}
